### ISSUE TITLE
Are the vault files needed in the RubyGems release?

### ISSUE THREAD

**Issue by mensfeld** [chrisliaw/liboqs-ruby#1]
Hey there,

While inspecting changes in this lib, I noticed that `mnt/Vault/08.Dev/01.Workspaces/` data is present. Is it needed? It seems like it was accidentally added there.

If I'm wrong feel free to close this issue and sorry :pray:

**Comment by chrisliaw** [comment]
Hi! May I know where did you find it? 

No that's basically a leak of private info as that's path in my local machine.

Thanks!

**Comment by mensfeld** [comment]
@chrisliaw hey, would you mind dropping me a line at maciej@mensfeld.pl? Since it's private info I would rather not share it here and we can move the conversation there to keep the info safe.
